apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: stefaniritter/hello-app:3c48affc36b64ecd85c9070578c8a68a42db6c5d
          ports:
            - containerPort: 8000
