apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: stefaniritter/hello-app:127c59a35da52f2ac75ed8c813a8506a2d47dabf
          ports:
            - containerPort: 8000
