apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloApp-deployment
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: stefaniritter/hello-app:e849079ed55cb5946363fba6936e5310919860cc
          ports:
            - containerPort: 8080
